# Generated by Django 2.1 on 2020-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ('name',), 'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
    ]
