# Generated by Django 2.1 on 2020-04-05 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('use_api', '0002_auto_20200405_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
