# Generated by Django 2.0 on 2020-04-15 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_api', '0003_api_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
                ('user_type', models.IntegerField(choices=[(1, '普通管理员'), (2, '超级管理员')], verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户模型',
                'verbose_name_plural': '用户模型',
                'db_table': 'userinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 16, 42, 55, 290232), verbose_name='添加时间')),
                ('user', models.OneToOneField(on_delete=False, to='use_api.UserInfo')),
            ],
            options={
                'verbose_name': '用户Token',
                'db_table': 'user_token',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='api',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
        migrations.AlterModelTable(
            name='api',
            table='api',
        ),
    ]
